CLI excersise
TanVD/se-architecture-course pull request #1
Opened 2019-02-09 12:24 UTC by TanVD

2019-02-17 02:19 UTC, artbez requested changes

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/EventLoop.kt
> +        } catch (e: ExitException) {
Лучше добавить обратку остальных исключений. Если строчка не валидна, лучше просто сказать об этом пользователю

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/EventLoop.kt
> +        println(String(result))
При команде X=1, появится лишний перенос строки

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/GlobalContext.kt
> +                    curLine += curChar
Лучше использовать StringBuilder, иначе квадратичная сложность

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/GlobalContext.kt
> +    fun expand(line: String): String {
Здесь никак не обрабатываются ситуации типа ```echo hello '```, когда нету парной ковычки.
Shell в таких случаях требует закончить строчку (парной ковычкой) уже на следующей строке. Если предполагается, что данная реализация не поддерживает перенос строк (а лучше поддержать), то хорошо бы предупредить пользователя об этом.

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Parser.kt
> +            "=" to name.split("=")
Если params не пусто, то тоже хорошо бы сообщить пользователю, что что-то введено не так

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Parser.kt
> +        val values = command.split(Regex("\\s+")).map { it.trim('"', '\'') }
echo '<много пробелов>hello<много пробелов>' должна выводить 
<много пробелов>hello<много пробелов>

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Parser.kt
> +    private fun splitByPipes(line: String, quotes: List<Char>): List<String> {
Метод частично дублирует логику метода expand класса GlobalContext. Было бы здорово вынести ее.

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    protected val params = inParams.map { it.trim().trim('"', '\'') }
Можно один trim

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    abstract fun execute(inputStream: InputStream): ByteArray
Наверное, лучше возвращать тоже Stream. Например, shell спокойно съест строку типа ```cat test.txt | cat```

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +        fun create(name: String, params: List<String>): Command {
Если в теле метода один return, можно сразу равно писать
```
fun create(name: String, params: List<String>) =
            commands[name.toLowerCase()]?.invoke(params) ?: ExternalCommand(name, params)
```

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    override fun equals(other: Any?): Boolean {
Насколько я вижу, нигде не используется

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    companion object {
Было бы здорово выделить отдельный Factory класс. Различных команд может быть много, так не будет перегружен класс Command.

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +class CommandChain(private val commands: List<Command>) : Command(emptyList()) {
Не уверен, что CommandChain является Command. Она не пользуется параметрами и ей не нужен inputStream. Да и по сути, она не применяется от аргументов, а чисто исполняет команды

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/ExitCommand.kt
> +        throw ExitException()
Выход из консоли это вполне валидное действие. Было бы здорово придумать другой механизм кроме как выкидывать исключение. В конце концов shell не умирает, если там написать ```exit | wc```

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/WcCommand.kt
> +        val input = if (params.none { it.isNotBlank() }) inputStream else File(params.first()).inputStream()
Не очень понял смысл этой строчки, но в любом случае, лучше избегать двойного отрицания
```params.any { it.isBlank() }```

2019-02-17 02:19 UTC, artbez commented on gel/src/test/kotlin/tanvd/gel/ContextTest.kt
> +    fun expand_constructFullyOperation_rendered() {
В котлине можно писать названия тестов в духе. Тогда можно избавиться от символа _.
```
@Test
    fun `my super test`() { ... }
```

2019-02-17 02:19 UTC, artbez commented on gel/src/test/kotlin/tanvd/gel/ContextTest.kt
> +class ContextTest : TestBase() {
Было бы здорово добавить тесты на "плохие" сценарии. Когда программа не может обработать пользовательский ввод, например.

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/CatCommand.kt
> +        return File(params.first()).readBytes()
Если у нас файл не найден, вылетим с ```java.io.FileNotFoundException```

2019-02-17 02:19 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +    override fun execute(inputStream: InputStream): ByteArray {
```
override fun execute(inputStream: InputStream) = commands
.foldRight(inputStream) { command, acc -> command.execute(acc).inputStream()}
.readBytes()
```

2019-02-17 18:32 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +        fun create(name: String, params: List<String>): Command {
Это правда, но я обычно так не делаю когда приходится из-за этого переносить на новую строчку или логика нетривиальная.

Всё же `fun a() = ...`, на мой взгляд, это возможность писать очень простые функции (как правило чистые) во многом обобщающая такие функции с просто полями (откуда и синтаксис такой).

Здесь, мне показалась логика нетривиальной и я бы лучше оставил внутри скобок, чтобы этим отдельно привле

2019-02-17 18:33 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    override fun equals(other: Any?): Boolean {
Действительно, мысль была изначально их самих в Map пихать, а `data` не поставить так как `abstract class`. Сейчас уже не нужно.

2019-02-17 18:39 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    companion object {
Тут я бы предложил другое решение. На мой взгляд `companion object` интерфейса вполне удачное место для фабрики, которая объекты этого интерфейса порождает (так как такой интерфейс используется только в связке с фабрикой как правило), однако действительно он может быть перегружен многочисленными командами.

Если команд было бы больше вполне небольшого конечного числа, я бы использовал вместо явной регистрации их в map (как сейчас), подход с инверсией зависимостей. В данном случае просто рефлексией искал бы классы помеченные `AutoRegister` (а `Command` был бы отнаследоваен от `AutoRegister`) и вызывал у них функцию `register`. Эта функцию в свою очередь была бы реализована в `Command` и как раз бы добавляла `this` в мапу в `companion object`. Такое решение сохраняет локальность кода команд и при этом не загромождает его. Тем не менее сейчас мне кажется это очень большим оверкиллом и явным нарушением KISS :)

2019-02-17 18:45 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +class CommandChain(private val commands: List<Command>) : Command(emptyList()) {
Мне кажется является, как минимум с точки зрения предметной области -- команды представляются замкнутым множеством относительно операции `|` и результат их соответственно тоже является командой .

Более того CommandChain пробрасывает inputStream в первую команду и это может быть полезно если потребуется всё же поддержать команды, перехватывающие ввод из консоли

2019-02-17 18:46 UTC, TanVD commented on gel/src/test/kotlin/tanvd/gel/ContextTest.kt
> +    fun expand_constructFullyOperation_rendered() {
Да, только от страшнущих camelCase предложений это не избавляет :( А мне кажется тут скорее это проблема :)

2019-02-17 20:29 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +        fun create(name: String, params: List<String>): Command {
Здесь комментарий случайно обрезан.. Предполагаю, что основная мысль ---  отдельно привлечь внимание к тому, что выполняются сложные вычисления. Если вычисления сложные, их следует разбить на более простые, выделив отдельные переменные (длинные, сложные цепочки хуже читаются). Получилось бы 
```
fun create(name: String, params: List<String>): Command {
  val commandProducer = commands[name.toLowerCase()] ?: { ExternalCommand(name, params) }
  return commandProducer.invoke(params)
}
```
Что мне, кстати, нравится меньше. 

Мой комментарий был нацелен на то, что можно записать более компактно, но а вообще, это дело вкуса конечно. Кому как удобней :)

2019-02-17 20:47 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    companion object {
Пока команд немного, действительно, фабрику разумно держать в компаньене, согласен.

Второе решение сильно напоминает бины в спринге, которые бы инициализировались и регистрировали бы себя в мапе команд, что вполне типично для приложения на спринге. Тут кстати встает вопрос о том, что же все-таки лучше: использовать xml и code-based для инициализации бинов. С одной стороны круто, что мы можем просто написать класс, отнаследовать от интерфейса (или добавить аннотацию) и вуаля, у нас уже +1 команда. С другой стороны, если все команды добавляются в коде, но в одном месте, они все всегда перед глазами. Мы можешь их группировать, комментировать группы, видеть похожие.

2019-02-17 20:50 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    companion object {
Ну тут можно аппелировать к общей идее Kotlin как языка с расширенной поддержкой IDE (отсюда например рекомендации не указывать типы, когда можно, в полной противоположности с  использованием `auto` в C++). В данном случае IDEA умеет показать всех наследников и раз свойство саморегистрируемости распротраняется во все наследники -- этого должно быть достаточно :)

2019-02-17 20:58 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    companion object {
Не, то что это будет работать, это, безусловно так. И мы легко и просто можем перейти к любому наследнику. Да даже группировку мы можем реализовать с помощью пакетов (раскидать по разным папочкам в зависимости от типов).

Но вот если у нас появится разные версии шела, которые будут реализовывать одни и те же интерфейсы командной строки, но поддерживать немного разный набор команд, например, в зависимости от операционки. В этом случае удобнее иметь 2 xml (или две фабрики).

2019-02-17 21:28 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +class CommandChain(private val commands: List<Command>) : Command(emptyList()) {
Мне понравился аргумент про замкнутость. Но тогда, мне все таки не совсем ясно, почему класс Command так называется.

В моем понимании команда командной строки это команда сама по себе, без конкретных аргументов, которая умеет в некотором контексте исполняться от указанных аргументов и возвращает какой-то результат. 
```
interface Command<Context, Result> {
  operator fun Context.invoke(params: List<String>): Result
}
```
Так командами являются cat или wc. 

Здесь, на мой взгляд, больше Execution, чем Command, и, действительно, они замкнуты относительно операции `|` и цепочка вычислений --- есть вычисление. 

В данной реализации CommandChain является объектом верхнего уровня, который, как мне кажется, не задумывался как что-то, что будет дальше комбинироваться с чем-нибудь другим. Таким образом inputStream, который он передает первой команде, всегда System.in. Если избавиться от родительского интерфейса Command, упростится интерфейс CommandChain. Если я не прав и CommandChain дальше планирует проявлять себя как Command, то, конечно, ок

2019-02-17 21:31 UTC, artbez commented on gel/src/test/kotlin/tanvd/gel/ContextTest.kt
> +    fun expand_constructFullyOperation_rendered() {
camelCase был придуман, чтобы писать несколько слов слитно. Таким способом слова можно писать отдельно:) Например, вместо `exitCommand_echoConsole_exceptionThrown` можно написать 
```
fun `throw ExitException when call exit'() { ... }
```

2019-02-17 21:33 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +    override fun execute(inputStream: InputStream): ByteArray {
Хм, тут мне кажется дело вкуса. Дело в том, что с одной стороный такой код вроде как и короче и понятнее для людей знакомых со свертками, с другой стороны он требует знания понятия свертка :) Я бы оставил как есть как раз из расчета на то, что мой код более дубовый и процедурный, но имеющий меньший порог вхождения)

2019-02-17 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +    override fun execute(inputStream: InputStream): ByteArray {
Согласен)

2019-02-17 21:48 UTC, TanVD commented on gel/src/test/kotlin/tanvd/gel/ContextTest.kt
> +    fun expand_constructFullyOperation_rendered() {
В принципе да, но мне как-то страшно становится за Java interoperability и то, как всё это будет переваривать библиотеки для инструментирования кода типа jacoco или просто тест-платформы. Тот же Dalvik на Android такие функции не поддерживает.

Кроме того сама команда Котлина тесты называет по [старому](https://github.com/JetBrains/kotlin/blob/master/compiler/tests/org/jetbrains/kotlin/daemon/CompilerDaemonTest.kt). Хотя фича действительно занимательная, я как-то никода не думал использовать методы с пробелами в тестах :)

2019-02-18 08:47 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    abstract fun execute(inputStream: InputStream): ByteArray
Не очень понял, в данной реализации (и по заданию) предполагается что через pipe весь output проходит разом (хотя это неправда для обычного Shell, где используется что-то типа PipedInput/OutputStream). Поэтому и я заворачиваю сразу всё в ByteArray, чтобы передавать в памяти

2019-02-18 08:49 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/CommandChain.kt
> +class CommandChain(private val commands: List<Command>) : Command(emptyList()) {
Разумно, переделал отдельно)

2019-02-18 08:58 UTC, TanVD commented
Добавил исправления

2019-02-18 21:06 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/Command.kt
> +    abstract fun execute(inputStream: InputStream): ByteArray
Вот я что-то такое и имел ввиду, но раз разом, то окей:)

2019-02-21 21:38 UTC, artbez requested changes
Супер! Классная реализация. Осталось по мелочи совсем поправить.

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Parser.kt
> +                curLine = StringBuilder(part.part.drop(1))
Мелкое замечание. Зачем каждый раз создавать новый объект, если можно вызвать метод clear?

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Shell.kt
> +                (e.message ?: "Illegal argument").toByteArray()
Может быть добавить логирование? Чтобы у нас остались записи какую строчку в каком контексте мы не смогли обработать. Конечно, на консоль логи выводить не надо... Можно в файл какой-нибудь

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Shell.kt
> +                (e.message ?: "Illegal argument").toByteArray()
Что насчет других ошибок? Мы их не ожидаем, но мы не все можем знать наверняка. В этом случае можно вывести сообщение из разряда "Не смогли обработать строчку".

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/ExternalCommand.kt
> +            if (e.message?.contains("error=2") == true) {
Было бы здорово добавить комментарий, который поясняет, что значит строчка "error=2"

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/ExternalCommand.kt
> +            throw e
Но обрабатываемое исключение

2019-02-21 21:38 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/utils/ParsingUtils.kt
> +        return lastPart == null || lastPart.part.firstOrNull() !in quotes || (lastPart.part.first() in quotes
Было бы здорово выделить здесь части и засунуть в отдельные переменные

2019-02-24 21:55 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/Parser.kt
> +                curLine = StringBuilder(part.part.drop(1))
Резонно :)

2019-02-24 22:00 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/command/ExternalCommand.kt
> +            throw e
Не понял :) На всякий случай добавил в документаци `@throws`, но вообще тут мы пробрасываем исключение если его не знаем и потом напечатаем в консоль

2019-02-24 22:08 UTC, TanVD commented on gel/src/main/kotlin/tanvd/gel/Shell.kt
> +                (e.message ?: "Illegal argument").toByteArray()
Ну, мне кажется это может быть не очень ожидаемым поведением. Нужно в таком случае лог ротейтить (иначе консоль просто исполняя в цикле неверную команду забьет весь диск), а это уже задача интересная, но выходящая сильно за рамки задания (там же надо будет и дать возможность место под лог конфигурировать, и желательно его формат и т.д.) На мой взгляд вариант с печатью в консоль сообщения о невалидности строчки вполне соответствует KISS и не переусложняет вещь, которая должна быть простой, надежной (и немного дубовой)

2019-02-24 22:26 UTC, TanVD commented
Добавил исправления :)

2019-02-25 09:43 UTC, yurii-litvinov approved these changes
Мне тоже всё нравится, зачтена

2019-02-25 10:03 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/Shell.kt
> +                (e.message ?: "Illegal argument").toByteArray()
Окей:)

2019-02-25 10:05 UTC, artbez commented on gel/src/main/kotlin/tanvd/gel/command/ExternalCommand.kt
> +            throw e
Не, это было все к тому, что вполне мб исключение, которое мы не ожидаем. Пофикшено добавление еще одного catch

2019-02-25 10:06 UTC, artbez approved these changes

2019-04-14 17:11 UTC, merged