Business process diagrams exercise
TanVD/se-architecture-course pull request #3
Opened 2019-02-20 18:02 UTC by TanVD

2019-05-28 09:27 UTC, yurii-litvinov requested changes
На контекстной IDEF0-диаграмме:
- Я бы сказал, что текущее состояние конвейера --- внутреннее дело процесса сборки, не стоит его рисовать как внешнее управление. То же, но в меньшей степени, касается плана поставок комплектующих --- возможно, процесс выполнения заказов включает в себя планирование поставок, и тогда его не надо рисовать тут. Возможно нет, тогда процесс выполнения заказов вписывается в более общий бизнес-процесс завода, но тогда это несколько нарушает требования условия :)
- Нету результата процесса.
- Я думаю, стоило бы отобразить сторудников как механизм, было бы плохо, если бы руководство про них забыло
- На диаграмме первого уровня "план производства" вряд ли материал для производства, скорее управление
- И я бы ещё процесс ремонта как-то отобразил, мы ведь в конечном итоге планируем разрабатывать приложения для учёта дефектов, так что хотим понимать место нашего приложения в общем бизнес-процессе
- BPMN-диаграмма подозрительно напоминает https://github.com/akhoroshev/se-architecture-course/blob/c3a64f778a7f9849dc92fee654b819c03f18ef5a/diagrams/BPMN.png, хотя Ваш вариант мне больше нравится :)
- К тому же, "Возврат на шаг обнаружения дефекта" рисуется как стрелка, а не как активность
- И сообщения вроед можно слать только между пулами, в рамках одного бизнес-процесса можно только передавать управление напрямую.
- Use Case диаграмма ок, разве что можно было бы границу системы явно нарисовать (вроде в UML 2.0 она более-менее обязательна).

2019-06-12 16:43 UTC, TanVD commented
1 - fixed
2 - fixed
3 - fixed
4 - fixed
5 - не совсем понимаю как ремонт отобразить на IDEF так как там ветвления нету :(
7 - а какая именно стрелка? Пока поставил intermediate
8 - у меня сообщения вроде везде между пулами шлются :)

2019-06-12 16:46 UTC, TanVD commented
Поправил замечания @yurii-litvinov

2019-06-17 12:54 UTC, yurii-litvinov commented
>5 - не совсем понимаю как ремонт отобразить на IDEF так как там ветвления нету :(
В IDEF рисуется схема процесса, то есть что в принципе может происходить. То есть можно просто нарисовать процесс "Отремонтировать автомобиль", в него стрелку из "Произвести автомобиль" с надписью "Повреждённый автомобиль".

>7 - а какая именно стрелка? Пока поставил intermediate
Просто передача управления на один из этапов (может, с ветвлением, которое явно показывает, что если дефект выявлен на этапе покраски, надо возвращать на этап покраски). Можно было бы "Ремонт" сделать исключительной ситуацией (блок с молнией), тогда возврат явно можно было бы не рисовать.

2019-06-18 07:39 UTC, TanVD commented
Добавил исправления

2019-06-18 16:12 UTC, yurii-litvinov commented
Так неповреждённый автомобиль же тоже может быть результатом процесса испытаний :) Это была бы просто вторая стрелка, которая выходит из этого процесса. Или даже так --- выходит стрелка "Автомобиль", которая делится на две --- повреждённый и исправный автомобиль. Но всё остальное теперь правильно, так что зачтена

2019-06-20 15:20 UTC, closed without merging