Bookstore diagrams
TanVD/se-architecture-course pull request #5
Opened 2019-03-17 17:35 UTC by TanVD

2019-05-23 23:59 UTC, artbez requested changes
1) Не вижу сущности веб-интерфейс. Так же как и сущности веб-сервис. Хотя по условию, 
> Интернет-магазин должен иметь веб-интерфейс, но он должен иметь возможность подключения через другие интерфейсы (веб-сервисы и т.п.)
2) Мб стоит выделить отдельную сущность под оплату? Которая бы ассоциировалась с PaymentMethod?
3) Нужно добавить методы по работе с корзиной: добавить/удалить книгу. То же проделать и с остальными сущностями. Например, отмена заказа.
4) Отсутствуют сущности для аутентификации пользователя и базы данных
5) Не нашел описание средств поиска. 
> Пользователь должен иметь возможность искать книги различными способами поиска – по заголовку, по автору, ключевому слову или категории и после поиска просматривать детальное описание книги.
6) Присутствует сущность Review, но интерфейсы взаимодействия с ней найдены не были

2019-06-12 15:48 UTC, TanVD commented
1 - fixed, но вообще это кажется лучше на компонентной диаграмме отображать
2 - выделил
3 - fixed, но не добавлял я их чтобы не перегружать схему. Эскиз выглядит понятнее.
4 - fixed
5 - fixed
6 - fixed, связи указал через атрибуты чтобы не перегружать диаграмму стрелками

2019-06-12 15:49 UTC, TanVD commented
Поправил замечания @artbez

2019-06-13 22:55 UTC, artbez requested changes
На компонентной тоже можно отобразить. Тут же, как ты правильно добавил, требовалось указать, что есть такой API. Есть некоторый интерфейс, с которым взаимодействуют две отдельные сущности: WebInterface и OtherIntegration.
> 1 - fixed, но вообще это кажется лучше на компонентной диаграмме отображать

Это учебное задание, поэтому нужно подробно детализировать диаграмму :)
> 3 - fixed, но не добавлял я их чтобы не перегружать схему. Эскиз выглядит понятнее.

Super
> fixed, связи указал через атрибуты чтобы не перегружать диаграмму стрелками

Теперь я стал лучше понимать схему и появилось еще несколько небольших  вопросов/замечаний. И одна большая просьба: указывать множественность с двух сторон от стрелки. Например A -1 -----*->B.
1. Не очень понимаю, почему между WaitingList и User множественная агрегация. 
1.1 Если WaitingList создается для одного пользователя, то User управляет его жизненным циклом, и тогда тут скорее либо композиция, либо ассоциация (не очевидно, почему User - WhishList это целое-часть).
1.2 Если WaitingList общий для всех пользователей, то тут скорее простая ассоциация. Уже нельзя сказать, что WaitingList часть некоторой сущности User. В этом случае я понимаю выбранную множественность.

2. Вопросы по связи м/у User и Cart аналогичные пункту 1.1

3. Не очень понимаю сущность PaymentMethod. Почему она в композиции с User? Из схемы мне кажется, что это просто способ оплаты. Почему не ассоциация?

В остальном мне все нравится :)

2019-06-18 07:26 UTC, TanVD commented
1 - поправил
2 - поправил
3 - поправил

2019-06-18 07:26 UTC, TanVD commented
Поправил замечания @artbez

2019-06-18 16:28 UTC, yurii-litvinov commented
Я бы ещё сказал ревью расписать поподробнее, потому что есть редакторские ревью, которые без рейтинга и не требуют модерации. Но в целом всё так, да. Зачтена.

2019-06-20 15:20 UTC, closed without merging